version: '3.1'

services:
  postgres:
    image: divyenduz/postgres-with-data:0.0.2
    restart: always
    command: postgres -c 'max_connections=1' -c 'superuser_reserved_connections=0'
    ports:
      - 5433:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  pgbouncer:
    image: brainsam/pgbouncer:1.12.0
    restart: always
    environment:
      DB_HOST: postgres
      DB_USER: root
      DB_PASSWORD: prisma
      DB_port: 5433
      POOL_MODE: 'transaction'
      MAX_CLIENT_CONN: '2'
    ports:
      - 6433:6432

volumes:
  postgres:
